run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - gocyclo
    - dupl
    - goconst
    - gocritic
    - godot
    - gofumpt
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  godot:
    scope: declarations
    period: true
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - goconst
  max-issues-per-linter: 0
  max-same-issues: 0 